### ISSUE TITLE
path encoding的疑惑

### ISSUE THREAD

**Issue by forclh** [StupidThree/SIGformer#3]
![image](https://github.com/user-attachments/assets/b3e4d2c1-ec32-47b6-b132-87af38cba32f)
请问框图中这两个向量点积是如何在代码中体现的

**Comment by StupidThree** [comment]
逐个获取 $$\mathbf{o}$$ 中非零的位置对应的 $$\varphi$$ 值，然后以这些值构造稀疏矩阵。

1. 创建nn.Embedding作为 $\varphi$ ，编码每一种路径模式
https://github.com/StupidThree/SIGformer/blob/a9012db5c6e467a8d46702d10f0d0f699a4a2c31/code/model.py#L15

2. 采样的同时记录点对之间的路径模式，编码时获取每一组点对之间的路径模式
https://github.com/StupidThree/SIGformer/blob/a9012db5c6e467a8d46702d10f0d0f699a4a2c31/code/model.py#L35-L37

3. 构造稀疏矩阵
https://github.com/StupidThree/SIGformer/blob/a9012db5c6e467a8d46702d10f0d0f699a4a2c31/code/model.py#L44-L46

**Comment by forclh** [comment]
所以一次采样的点对是只考虑了一种路径吗？是否等同于为每一种路径类型编码了一个特征

**Comment by StupidThree** [comment]
> 所以一次采样的点对是只考虑了一种路径吗？

采样的时候，有可能会采样到两点之间的多条路径。比方说图中的 $$u_2$$ 和 $$u_3$$两点之间，可能采样到 $$u_2 - i_3 - u_3$$ 和 $$u_2 - i_4 - u_3$$两条路径。在构造稀疏矩阵时，会把两点之间采样到的每一种路径类型对应的 $$\varphi$$ 值累加，效果相当于一个01向量与 $$\mathbf{\varphi}$$ 作内积。

> 是否等同于为每一种路径类型编码了一个特征

是的。就是将每一种路径类型，编码为一个可学习的标量值。
