### ISSUE TITLE
对于KuaiRand数据集的一些问题

### ISSUE THREAD

**Issue by iHccob** [StupidThree/SIGformer#4]
在KuaiRand官方的介绍中，27k、1k和pure三个数据集中的用户数量分别是27k、1k和27k。这和kuairand目录下的info中所展示的有所不同，请问这是在训练前做了数据的清洗吗

**Comment by StupidThree** [comment]
是的～
就像我们在论文的实验设置中提到的，为了保证数据集中的用户和物品都有足够的历史交互数据体现他们的喜好和特征，我们做了5-core，即确保处理后的数据中每个用户和物品都有至少5条历史交互信息。
